### ISSUE TITLE
Profession Categories Not Switching Correctly + Not Creating Correct Item

### ISSUE THREAD

**Issue by Dean98** [b-morgan/Skillet-Classic#25] opened 2021-06-22 12:04 UTC
V1.28

When selecting engineering or smelting or cooking etc in the skillet window, it doesn't show the correct profession e.g. it shows that Engineering is active and even shows it in the skillet window title bar, but mining shows in the list. Or selecting cooking shows mining in the list. I have removed all WTF configs for Skillet and clean installed the addon, but it still persists.

Edit: I have just discovered also that it isn't showing all the correct items to craft e.g. Fel Iron Musket is not showing as a craftable item, but it is my current skill up item and doesn't show at all.

Edit: FYI I have reverted back to v1.26 (unsure if this was the version I used previously) and the issue in the first paragraph does not happen.

I was having another issue prior to this version that didn't create the item it said it was e.g. fel iron casing was creating fel iron bolts in reality. This may have been fixed in this version.

**Comment by b-morgan** [comment] 2021-06-22 13:40
I believe that there are multiple issues in play here. One is the issue of the wrong profession being displayed and the other is the wrong item being created.

The wrong item being created can be caused by queuing a item to be made, learning a new recipe, and then processing the queue. In Classic Era and Burning Crusade Classic, the Blizzard API for actually creating an item is `DoTradeSkill(recipeIndex, count)` (or `DoCraft(recipeIndex, count)`). When you learn a new recipe, it often changes the recipeIndex of most of the other recipes. In retail, the Blizzard API uses the recipeID in the call to create an item so this can't happen. I'll look into finding a way for the Skillet-Classic code to identify this condition.

The major change between 1.28 and 1.27 is in the way Skillet-Classic responds to opening or changing professions. This change was made to (hopefully) eliminate missing recipes and/or missing reagents which would occur occasionally in prior versions. It is  more in line with how the Blizzard UI works and I haven't seen the issue you describe. If you have to use an older version, 1.27 would be preferable over 1.26.

The recipes your character knows for each profession is stored on the server and is transferred to the client when you open a profession. This process is not instantaneous, and unfortunately, Blizzard did not provide a specific event for the completion of this transfer. 

The profession buttons in the Skillet-Classic frame do not generate the same sequence of events as closing one profession and opening another which can cause problems like you are seeing if a profession has not been opened and closed once using an action bar button or your Skills interface. Once opened and closed the "old fashioned" way which should get the client and server in sync, the buttons in the Skillet-Classic frame should function as expected.

If this doesn't explain the behavior you are seeing, then you will need to capture Skillet-Classic debugging information and upload it here. Let me know if we need to do this and I'll provide detailed instructions.

**Comment by b-morgan** [comment] 2021-06-23 19:39
Skillet-Classic-1.29-alpha2 contains changes which should help both of these issues. I'm not able to reproduce either issue.

For the case of queuing a recipe, learning a new recipe, and then processing that recipe, a warning message is sent to chat and the offending item is removed from the queue. To see the warning message, type "/skillet warnshow on". This code probably needs some changes.

In order to assure that Skillet-Classic has the correct recipe data from the server, the profession buttons in the Skillet-Classic frame are disabled until an action bar button is used to open each profession. A dialog is opened when this restriction hasn't been met.

**Comment by b-morgan** [comment] 2021-06-27 14:54
I believe that the current 1.29 alpha builds have resolved the issues raised here. Please open a new issue if any of these errors return.

**Closed by b-morgan** 2021-06-27 14:54 UTC
