### ISSUE TITLE
Enchanting broken

### ISSUE THREAD

**Issue by Dinoburt** [b-morgan/Skillet-Classic#78] opened 2022-08-31 18:47 UTC
Window does not indicate that there is an enchant already pending, so it keeps adding the enchant to a process queue that is not being indicated on the enchanting page. For example, guildie wanted mongoose, then changed their mind to executioner. Even when selecting executioner it is trying to do mongoose. Only way to see why there is an issue is going to another profession and clearing the queue. 
![ring enchant](https://user-images.githubusercontent.com/58857700/187757419-bb3fd1b8-3459-4c38-a2b4-33c0c0784a94.JPG)
![queue](https://user-images.githubusercontent.com/58857700/187757437-9c46118c-fc48-4ee7-94b7-7c296c3411d4.JPG)

youll see with the ring enchant since I tried healing power once, canceled it then selected Striking, it keep trying to process healing power. I don't know why there is a queue for enchanting.

**Comment by rushtothesun** [comment] 2022-08-31 22:56
Enchanting also doesn't show the tooltip of the enchant. So unless you already know what the enchant does you'll have to look up the enchant on wowhead or disable the addon.

**Comment by b-morgan** [comment] 2022-09-01 00:21
I hated Enchanting when Blizzard decided it was a craft and not a tradeskill in the first Classic release.

Now I hate Enchanting because Blizzard has converted it back to a tradeskill (but it isn't quite as complete as the retail implementation).

@rushtothesun, I have moved your comment to a new issue (#79)

@Dinoburt, There is a Skillet-Classic option "Queue Enchant reagents" and if you uncheck that, Enchants will not be queued. The reason for this option is so that you can fill the shopping list with the reagents needed for multiple enchants and then fetch any missing reagents from, for example, your bank. The tooltip for this option notes that Enchants can't be processed from the queue (and if they are in Wrath Classic, then that's another bug).

Stay tuned as I investigate.

**Comment by Dinoburt** [comment] 2022-09-01 01:06
> 
Reason I posted is it is queuing with the "queue enchant reagents" unchecked and just filling up the queue.

**Comment by b-morgan** [comment] 2022-09-02 16:08
I have built [Skillet-Classic-1.48-alpha1](https://www.curseforge.com/wow/addons/skillet-classic/files/3963905) which doesn't yet address this issue, but it has other enchanting related fixes.

I believe if you check the option "Queue Enchant reagents", it will expose the queue contents and the buttons necessary to clear the queue.

**Comment by b-morgan** [comment] 2022-09-03 17:09
I believe this is a duplicate of issue #82 so I'm closing this one.

**Closed by b-morgan** 2022-09-03 17:09 UTC
