### ISSUE TITLE
Enchanting missing icons and Info.

### ISSUE THREAD

**Issue by joltox** [b-morgan/Skillet-Classic#95] opened 2022-09-08 19:22 UTC
Issue: The window to right of the list does not display the enchant Icon or info. This only seems to affect the actual enchants as the weapon oils and wands and rods all show as usual.

**Comment by joltox** [comment] 2022-09-08 19:23
![Capture](https://user-images.githubusercontent.com/34920553/189208398-e233db05-4024-44de-aede-d07974ab2b15.PNG)

**Comment by b-morgan** [comment] 2022-09-08 19:36
Thank you for reporting this. It is a duplicate of issue #79 and is fixed in [Skillet-Classic-1.48-beta6](https://www.curseforge.com/wow/addons/skillet-classic/files/3973915).

**Closed** 2022-09-08 21:33 UTC
