### ISSUE TITLE
Skillet-Classic\UI\MainFrame.lua:978: attempt to index field 'subRanks' (a nil value)

### ISSUE THREAD

**Issue by boktai1000** [b-morgan/Skillet-Classic#71] opened 2022-02-09 03:02 UTC
1x Skillet-Classic\UI\MainFrame.lua:978: attempt to index field 'subRanks' (a nil value)
[string "@Skillet-Classic\UI\MainFrame.lua"]:978: in function `UpdateTradeSkillWindow'
[string "@Skillet-Classic\SkilletQueue.lua"]:51: in function `AdjustInventory'
[string "@Skillet-Classic\Skillet-20503.nil.lua"]:1238: in function `?'
[string "@Details\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...ils\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Details\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...ils\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Details\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@Attune\Libs\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <...aceAttune\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>
[220208_Skillet-Classic_LUA.txt](https://github.com/b-morgan/Skillet-Classic/files/8029055/220208_Skillet-Classic_LUA.txt)

**Comment by b-morgan** [comment] 2022-02-09 15:39
Either you are using an old version of Skillet-Classic or your download is corrupt.  MainFrame.lua:978 in the current version doesn't reference `subRanks`.

Assuming you can recreate this error with the current version, without some additional context like what were you doing when the error occurred will make it hard for me to figure out what is happening.

**Comment by boktai1000** [comment] 2022-02-09 15:50
My version of Skillet Classic (TBC) is 1.43 (20503)

![image](https://user-images.githubusercontent.com/9054563/153236602-d297e3b7-76c3-4dd0-beb8-f340af69cc0b.png)

![image](https://user-images.githubusercontent.com/9054563/153236667-241342b3-9c45-402a-8bab-e703402cdaaa.png)

Hashes of my file:
MD5 2FD0FACAB3F053C7838554968C78CB64
SHA1 535F84827B53F70BAAA36E6DD21BB08C98843AFE

Upload my Skillet install
[Skillet-Classic.zip](https://github.com/b-morgan/Skillet-Classic/files/8034008/Skillet-Classic.zip)

I don't believe my install is corrupt in any way, and the rest of my UI is just fine. It was a manual installation I performed shortly after patch 2.5.3 went out. I don't quite remember the context of when the error occured because it was grabbed with BugSack/BugGrabber and I noticed it during raid, so it's possible it happened during Black Temple.

**Comment by boktai1000** [comment] 2022-02-09 15:55
And if it helps any, the version of Skillet I'm using (I just cross referenced with a fresh download from Curseforge) is this one:

https://www.curseforge.com/wow/addons/skillet-classic/download/3612691
https://media.forgecdn.net/files/3612/691/Skillet-Classic-1.43-bcc.zip (the link it generated for me)

**Comment by b-morgan** [comment] 2022-02-09 16:54
My bad... I was looking at Skillet, not Skillet-Classic.

From the first screenshot you posted, it looks like you are running some additional trade skill addon. What is it?

I believe the first error you posted would only occur if Skillet:UpdateTradeSkillWindow() was called before Skillet:CreateTradeSkillWindow() was called or something corrupted the SkilletRankFrame. We may have to enable Skillet-Classic debugging and I may have to create a new version with additional debug statements to chase this one down if it is reproducable.

The second error you posted is a complete mystery. The only guess I can make from your location in the Netherwing Mines is that you entered combat because a mob spawned. I'm not sure Skillet-Classic has been hardened against entering combat unexpectedly. If you can find a quieter place to experiment and can reproduce the error, then I might be able to figure it out. Again, we may need to enable Skillet-Classic debugging.

Again, apologies for my mistake in looking at the wrong version of MainFrame.lua. Let's see if we can find reproducible cases so we can eliminate this error.

**Comment by boktai1000** [comment] 2022-02-09 16:59
> From the first screenshot you posted, it looks like you are running some additional trade skill addon. What is it?

I believe you're referring to All The Things, can be seen here: https://www.curseforge.com/wow/addons/all-the-things

![image](https://user-images.githubusercontent.com/9054563/153250759-01ab0e4a-53ec-4a18-bf3b-e4d064e09b30.png)

Glad to help with debugging or collecting more information, just let me know when it's convenient for you and I'll enable/collect anything necessary.

**Comment by b-morgan** [comment] 2022-02-09 17:26
First order of business is to see if either error is reproduceable. Much easier for me if I can generate the error(s) on my system but I can live with reproduceable issues on yours if necessary.

**Comment by boktai1000** [comment] 2022-02-09 17:55
Well not to overwhelm with LUA Errors and what not but I was in combat and tried to open my Enchanting frame to check something as I was running to Mara to get a Lunar Festival, and hit a Lua Error.

This one seems unrelated to the first one, but maybe more related to the second that I reported in regards to being in combat/etc. So just trying to collect it as I see it happen.

1x [ADDON_ACTION_BLOCKED] AddOn 'Skillet-Classic' tried to call the protected function 'SkilletQueueParent:Hide()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `Hide'
[string "@Skillet-Classic\UI\MainFrame.lua"]:567: in function `ConfigureRecipeControls'
[string "@Skillet-Classic\Skillet-20503.nil.lua"]:997: in function `?'
[string "@Details\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...ils\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Details\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...ils\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Details\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@Attune\Libs\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <...aceAttune\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>

![image](https://user-images.githubusercontent.com/9054563/153260742-fa6604cd-42df-45c0-91a9-d25807fd21b9.png)
[220209_Skillet-Classic_LUA.txt](https://github.com/b-morgan/Skillet-Classic/files/8035045/220209_Skillet-Classic_LUA.txt)

**Comment by b-morgan** [comment] 2022-02-09 18:20
It appears that Skillet-Classic doesn't work very well when in combat. 

Before I start the hardening process (which is probably going to be painful) I have to ask myself how many of my users try to craft while in combat. Then I ask what would be the result of this hardening process. My first guess would be that all crafting events would immediately exit if in combat.

What would be acceptable to you?

**Comment by b-morgan** [comment] 2022-02-09 18:23
BTW, there is a `<>` tool which can be used to insert the error text without GitHub markdown trying to fix it.

**Comment by boktai1000** [comment] 2022-02-09 20:25
I have to imagine that the main crafting in combat are either emergencies (Bandages,etc) or some one off attempts at crafting while going about daily business. Sometimes it can create clutch saves but the odds of something happening outside of a bandage craft in-combat is probably fairly low.

And I'm just one use-case really.

Appreciate the heads up with < > - I thought I've tried to use it before but still had characters escaped. Maybe I'm misremembering, but I'll go for it next time, it's definitely what I wanted/was going for :)

**Comment by b-morgan** [comment] 2022-02-09 20:52
I don't know about you but if I'm in combat and don't have any bandages, I'll be dead before I get some made!

In any case, I tried to reproduce any of your errors by attempting to craft a bandage while in combat. I was unsuccessful at both crafting a bandage or getting a Lua error. The only strangeness was that in some cases, the Blizzard UI opened instead of the Skillet-Classic UI.

I did install All the Things addon but it didn't seem to have any adverse interactions with Skillet-Classic.

I'm going to close this issue. Please reopen if you find a reproduceable case I can use.

**Closed by b-morgan** 2022-02-09 20:52 UTC
