### ISSUE TITLE
ADDON_ACTION_BLOCKED

### ISSUE THREAD

**Issue by StellarHarbour** [b-morgan/Skillet-Classic#114] opened 2022-09-26 15:10 UTC
1x [ADDON_ACTION_BLOCKED] AddOn 'Skillet-Classic' tried to call the protected function 'SkilletQueueAllButton:Show()'.
[string "@!BugGrabber\BugGrabber.lua"]:480: in function <!BugGrabber\BugGrabber.lua:480>
[string "=[C]"]: in function `Show'
[string "@Skillet-Classic\UI\MainFrame.lua"]:621: in function `ConfigureRecipeControls'
[string "@Skillet-Classic\Skillet-30400.nil.lua"]:981: in function `?'
[string "@Scrap\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...rap\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Scrap\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...rap\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Scrap\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@Scrap\libs\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <...faceScrap\libs\AceEvent-3.0\AceEvent-3.0.lua:119>
[string "=[C]"]: ?
[string "=[C]"]: in function `UseAction'
[string "@FrameXML\SecureTemplates.lua"]:343: in function `handler'
[string "@FrameXML\SecureTemplates.lua"]:625: in function <FrameXML\SecureTemplates.lua:569>
[string "=[C]"]: ?
[string "@FrameXML\SecureHandlers.lua"]:266: in function <FrameXML\SecureHandlers.lua:263>
[string "=[C]"]: ?
[string "@FrameXML\SecureHandlers.lua"]:296: in function <FrameXML\SecureHandlers.lua:279>
[string "=(tail call)"]: ?

**Comment by b-morgan** [comment] 2022-09-26 15:22
Can you tell me what you were doing at the time? 
Is this reproducible? If so, can you document the steps to take to reproduce it?
What version of Skillet-Classic? 
What professions?

The more data you can give me, the better chance I have of finding and fixing the problem.

**Comment by b-morgan** [comment] 2022-09-28 14:05
I'm guessing that you were crafting when you entered combat. For now, I suggest finding a safer place to craft.

**Comment by SegoItCh** [comment] 2022-09-29 05:37
Mining + Herbalism, didn't crafted anything for weeks :D

**Comment by b-morgan** [comment] 2022-09-29 12:18
> Mining + Herbalism, didn't crafted anything for week

Then I have no idea how this happened. `SkilletQueueAllButton:Show()` is only called (by my code) when the Skillet-Classic frame is open.

I'm closing this issue because I doubt I can find a solution given the circumstances of its occurrence.

**Comment by Alessandro-Barbieri** [comment] 2024-05-31 23:11
```
2x [ADDON_ACTION_BLOCKED] L'AddOn 'Skillet-Classic' a tenté d'appeler la fonction protégée 'SkilletQueueAllButton:Show()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `Show'
[string "@Skillet-Classic/UI/MainFrame.lua"]:622: in function `ConfigureRecipeControls'
[string "@Skillet-Classic/Skillet.lua"]:1031: in function `?'
[string "@Accountant_Classic/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...sic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Accountant_Classic/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...sic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Accountant_Classic/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Accountant_Classic/Libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...ccountant_Classic/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `CastSpellByName'
[string "@FrameXML/SecureTemplates.lua"]:379: in function `handler'
[string "@FrameXML/SecureTemplates.lua"]:625: in function <FrameXML/SecureTemplates.lua:569>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:491
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:557
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:557
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:551
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:566
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:511
}
```
same here when  crafting and entering in combat

**Comment by Alessandro-Barbieri** [comment] 2024-05-31 23:11
> I'm guessing that you were crafting when you entered combat. For now, I suggest finding a safer place to craft.

Can we get an actual fix instead of this?

**Comment by b-morgan** [comment] 2024-06-01 14:26
> Can we get an actual fix instead of this?

To fix it requires reliably reproduceable conditions and combat is anything but... In addition, I don't know which version of WoW, the version of Skillet-Classic or any other details that might prove useful.

If you can provide me with detailed steps that create this error then I'll look into it. For now, replace `...\Addons\Skillet-Classic\Skillet.lua` with the following and let me know what happens.

[Skillet.zip](https://github.com/user-attachments/files/15522151/Skillet.zip)

**Comment by b-morgan** [comment] 2024-06-02 12:27
I have re-read this issue and in two years there have been two occurrences. In both cases, I have asked for additional information and none has been provided. I have decided that reopening this issue is a mistake. If someone can provide the additional information I need, then I'll reconsider.

**Comment by Alessandro-Barbieri** [comment] 2024-06-02 14:23
skillet-classic-1.91-classic
server Gandling on classic era
remove all addons except skillet bugsack buggrabber addoncontrolpanel
get tailoring
attack a mob and then create a silk bolt while in combat

you'll get
```
3x [ADDON_ACTION_BLOCKED] L'AddOn 'Skillet-Classic' a tenté d'appeler la fonction protégée 'SkilletQueueAllButton:Show()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `Show'
[string "@Skillet-Classic/UI/MainFrame.lua"]:622: in function `ConfigureRecipeControls'
[string "@Skillet-Classic/Skillet.lua"]:1031: in function `?'
[string "@Accountant_Classic/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...sic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Accountant_Classic/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...sic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Accountant_Classic/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Accountant_Classic/Libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...ccountant_Classic/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `CastSpellByName'
[string "@FrameXML/SecureTemplates.lua"]:379: in function `handler'
[string "@FrameXML/SecureTemplates.lua"]:625: in function <FrameXML/SecureTemplates.lua:569>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:491
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:557
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:557
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:551
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:566
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:511
}
```

**Comment by b-morgan** [comment] 2024-06-02 15:37
I need a little more information. Can you expand "attack a mob and then create a silk bolt while in combat". Do you attack the mob and then open Skillet-Classic or is Skillet-Classic already open when you attack the mob?

What would you like to happen when this error occurs?

Blizzard is preventing Skillet-Classic from making changes to its frame. Skillet-Classic was designed to have a more informational and interactive crafting experience and testing for "in combat" at every API call that attempts to change the frame would be a massive undertaking.

Replace `...\Interface\Addons\Skillet-Classic\Skillet.lua` with the version in the following .zip file. This will prevent Skillet-Classic from opening if the player is in combat and will close the Skillet-Classic frame when the "ADDON_ACTION_BLOCKED" event occurs. Let me know if this is satisfactory.

[Skillet.zip](https://github.com/user-attachments/files/15525816/Skillet.zip)

**Closed** 2024-06-18 13:41 UTC

**Comment by Alessandro-Barbieri** [comment] 2024-06-21 01:17
> I need a little more information. Can you expand "attack a mob and then create a silk bolt while in combat". Do you attack the mob and then open Skillet-Classic or is Skillet-Classic already open when you attack the mob (i.e. I need the exact steps you used to create the error)?

My issue was when you attack first and the you open the profession.
I tried the suggested fix and it's working
