### ISSUE TITLE
No Reagents Listed

### ISSUE THREAD

**Issue by boktai1000** [b-morgan/Skillet-Classic#45] opened 2021-09-06 17:29 UTC
Hey there, I'm taking a tour of your addon - in particular I'm a fan of the fact that your Enchanting Frame (CraftFrame) is able to provide tooltips that work with my Bag addons (Bagnon, tdbag2) to show me how many materials I have and where they are.

One thing I've noticed though while browsing through a number of items I have, is there's no Reagents listed for some of the recipes in the window. Here's a screenshot of an example, it's not everything - but definitely quite a few I've come across. On my Shaman who is a beginner Enchanter, it was every recipe - but on my Warrior who's a Blacksmith - it wasn't everything, but definitely a number of items.

![image](https://user-images.githubusercontent.com/9054563/132249079-a5bb2818-bf64-401c-8e39-c05307eab876.png)

**Comment by boktai1000** [comment] 2021-09-06 17:50
Here's an example on my Warrior with reagents showing

![image](https://user-images.githubusercontent.com/9054563/132250380-8b18df72-ee88-4533-8aec-45f7c7d4fe17.png)


Then another example where it isn't

![image](https://user-images.githubusercontent.com/9054563/132250411-da79bcd9-9d37-4fa2-9edf-4b07a2e2c4ec.png)

**Comment by b-morgan** [comment] 2021-09-06 18:01
This is a duplicate of #40. That issue was closed because I suggested a possible fix but got no response if it worked or not.

The line numbers have changed since that issue. Lines 841 and 862 in Skillet-Classic-1.34-alpha3. Lines 845 and 866 in Skillet-Classic-1.33.

Closing Skillet-Classic and opening it again usually fixes the issue. In my experience, it only happens the first time you open your professions after logging in.

There are other debugging options we can explore if you have a solid, reproduceable case. I'd love to fix this once and for all.

**Comment by boktai1000** [comment] 2021-09-07 17:33
I uncommented those lines that you mentioned in Skillet-Classic-1.33 and still having the issue

![image](https://user-images.githubusercontent.com/9054563/132387055-3fafca33-721b-4218-b9d6-38bc01256036.png)

**Comment by boktai1000** [comment] 2021-09-07 17:37
I also noticed a very odd issue where after I closed Skillet, clicking any of my profession buttons in my UI opened my bags. This is likely a different issue altogether, and I don't want to muddy the waters. But I'm going to mention it simply for the sake of me not forgetting about it, and it's hard to capture in a screenshot. I think it might be because my Bag addon (tdBag2) opens bags when the profession pane opens automatically, but for whatever reason - the profession pane for Skillet simply wasn't opening, so it appeared as if it was just opening my bags. This happened via my buttons on my actionbar, and through the spellbook when attempting to open.

Again- apologies as this is likely unrelated to the issue I opened here - I just wanted to mention it in the off chance it's related, as well as so I don't forget.

Disabling Skillet caused this to work again.

**Comment by b-morgan** [comment] 2021-09-07 19:48
If you don't want to forget this bags thing, please open a new issue.

Skillet-Classic has a debug logging feature which can output to chat and/or output to the per character saved variables file. The output to file is limited in size (an in memory buffer) that gets written each time a character logs out or reloads the UI.

We need to enable this output so you can send it to me. First, type "/skillet warnshow on" and "/skillet traceshow on". This will enable output to both chat and the saved variables file. "/skillet traceshow off" will turn off output to chat but keep output to the saved variables file, and "/skillet tracelog off" will turn that off as well. "/skillet warnshow off" and "skillet warnlog off" do the same but I think you will want to leave warnings to chat on.

When you open Skillet-Classic and notice that recipes are incomplete, close Skillet-Classic and open it again. You should see warning messages appear as Skillet-Classic corrects the bad recipe data with better recipe data. Skillet-Classic still has no way to know if the server has reported everything to the client (it is just processing what the client tells it) so you can repeat this process if necessary.

The trace output shows all of the events that Skillet-Classic has registered for. The events we are most interested in for this issue  are TRADE_SKILL_SHOW and TRADE_SKILL_UPDATE. There should be one TRADE_SKILL_SHOW when you click a profession buttton and then multiple TRADE_SKILL_UPDATE events as the data from the server to the client is updated. The problem is that there isn't a fixed number of update events and there's no event that indicates we got the last update. The code you uncommented assumes there will always be at least 2 so it ignores the first one. Changing the number to 3 (or more) will have a better chance of waiting until all the data is updated in the client, but has the risk that we end up waiting for one that will never arrive.

I'd like to see this output from your system so I can compare it to what I see on mine. What I want is a failure case so when you see a bad recipe, close the Skillet-Classic frame and logoff, make a copy of that character's saved variables file and then attach it here. Github doesn't like .lua files so either change the extension to .txt or zip the file. If you want to capture multiple failures, rename the files so each is unique and zip all of them together and attach here.

Depending on what I see in your files, I may want to add more debug output and enable that as well.

Note: Skillet-Classic-1.34-alpha3 (or higher) has a .toc update for 2.5.2 and some other small fixes. It should be stable for you you to use it instead of 1.33.

**Comment by b-morgan** [comment] 2021-09-16 19:02
Without additional input I can't do anything about this issue so I'm closing it. Please reopen this issue or open a new issue if you wish to pursue this further.

**Closed by b-morgan** 2021-09-16 19:02 UTC
