### ISSUE TITLE
Enchanting stuck in tradewindow

### ISSUE THREAD

**Issue by Raithen88** [b-morgan/Skillet-Classic#82] opened 2022-09-01 17:32 UTC
There also is a second bug:

If you want to enchant somebody, but then delete the loaded enchant, it's stuck. You have to reload UI.

**Comment by b-morgan** [comment] 2022-09-02 16:12
I don't understand "stuck". Please provide a better set of steps to reproduce this issue.

I have built [Skillet-Classic-1.48-alpha1](https://www.curseforge.com/wow/addons/skillet-classic/files/3963905) which doesn't yet address this issue, but it has other enchanting related fixes.

I believe if you check the option "Queue Enchant reagents", it will expose the queue contents and the buttons necessary to clear the queue.

**Comment by Raithen88** [comment] 2022-09-03 01:12
After some dozen enchantings, I figured it out.
In a trade, the enchanting qeue has to be cleared. Then it's fixed. It would be nice, if a trade won't stay in the "qeue".
The deleting-qeue mechanic is the problem.

**Comment by b-morgan** [comment] 2022-09-03 17:00
Enchanting in Classic Era (and Burning Crusade Classic) was a Craft, not a TradeSkill. To make it more exciting, it used the Blizzard API call DoCraft instead of DoTradeSkill and Blizzard made DoCraft a restricted call so Skillet-Classic had to steal the Enchant button out of Blizzard's CraftFrame to make things work. At the request of a user, queuing of Enchants (for the purpose of queuing the reagents) was added (controlled by an option).

Blizzard changed Enchanting in Wrath of the Lich King Classic to a TradeSkill and added the ability to apply enchants to vellums to create scrolls which can be traded in the Auction House.

The current implementation for TradeSkills in Skillet-Classic is to always add things to a queue and then process that queue if  the Create, Create All, or Process buttons were pressed. The option, "Queue enchant reagents" alters the visibility of the buttons and the queue. I think you want this option checked so that you can see the queue and hit the clear button if you see enchants that should not be there.

I am listening to your input because I am not a "professional" enchanter. I have toons with enchanting so I can debug Skillet-Classic (and my disenchanter is level 35, enchanting 275 to create Arcane Dust for my 375 Tailor). 

I want to find a solution that works for you and everyone else and I'm trying to avoid a complete rewrite of the queuing code separating it into two paths, enchanting and everything else. I currently am trying the approach of always adding enchants to the beginning of the queue. I think the idea of having a queue of enchants so you can gather mats and vellums using the shopping list is a good feature to have. I believe this means wholescale deleting enchants from the queue might not be the best solution.

Complicating the progress is that there is currently only one set of source for Classic Era and WotLK Classic. I have to test on both to make sure I don't break Classic Era while attempting to fix Wrath.

If you would like to try my "enchants first" implementation, install Skillet-Classic-1.48-alpha2 and replace SkilletQueue.lua with this one.
[SkilletQueue.zip](https://github.com/b-morgan/Skillet-Classic/files/9483029/SkilletQueue.zip)

**Comment by b-morgan** [comment] 2022-09-03 17:04
Hmmm... If enchants are always added to the beginning of the queue then could I just process enchanting queue entries only if they are in position 1?

**Comment by b-morgan** [comment] 2022-09-05 16:17
[Skillet-Classic-1.48-alpha3](https://www.curseforge.com/wow/addons/skillet-classic/files/3969833) includes the enchants are always queued to the front change.

**Comment by b-morgan** [comment] 2022-09-08 21:39
Skillet-Classic-1.48-beta6 has code to empty the queue of all enchants before processing a new one if the Skillet-Classic option "Queue enchant reagents" is not checked. If the option is checked, then the queue is visible and can be cleared at any time. In addition, enchants are always queued at the beginning of the queue.

I believe these changes address all the concerns mentioned in this issue so I am closing it. Reopen it or create a new one if additional issues arise.

**Closed by b-morgan** 2022-09-08 21:39 UTC
