### ISSUE TITLE
SkilletData.lua:565: attempt to index field '?' (a nil value)

### ISSUE THREAD

**Issue by class2u** [b-morgan/Skillet-Classic#33] opened 2021-07-13 09:17 UTC
Thank you for making this great addon. I get this error when clicking the small icons to change profession. The first time I click it popup a message "Use Action Bar button to change professions". Then I close and reopen Skillet-Classic window and click it again. I get the error or change to wrong profession. I am using Skillet-Classic 1.30-classic.
```
19x Skillet-Classic\SkilletData.lua:565: attempt to index field '?' (a nil value)
[string "@Skillet-Classic\SkilletData.lua"]:565: in function `GetSkill'
[string "@Skillet-Classic\SkilletData.lua"]:638: in function `CalculateCraftableCounts'
[string "@Skillet-Classic\SkilletQueue.lua"]:32: in function `AdjustInventory'
[string "@Skillet-Classic\SkilletQueue.lua"]:561: in function `ContinueCast'
[string "@Skillet-Classic\SkilletQueue.lua"]:478: in function `?'
[string "@!!!EaseAddonController\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...ler\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@!!!EaseAddonController\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...ler\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@!!!EaseAddonController\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@!!!EaseAddonController\Libs\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <...seAddonController\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>
[string "=[C]"]: in function `CastSpellByName'
[string "@Skillet-Classic\Skillet-20501.nil.lua"]:1354: in function `ChangeTradeSkill'
[string "@Skillet-Classic\Skillet-20501.nil.lua"]:1415: in function `SetTradeSkill'
[string "@Skillet-Classic\UI\MainFrame.lua"]:668: in function `TradeButton_OnClick'
[string "*:OnClick"]:2: in function <[string "*:OnClick"]:1>
```

**Comment by b-morgan** [comment] 2021-07-13 11:49
I cannot reproduce this error with the description you have given. Please give me more specific detail on the steps you take to cause this error. Something like:

1. Logon
2. Open Skillet-Classic using an action bar button assigned to xxx profession.
3. Click on Skillet-Classic profession button yyy.
4. The popup message appears (and the Skillet-Classic window closes by itself?)
5. Open Skillet-Classic using an action bar button assigned to ??? profession.

If I cannot reproduce your error, then I will need you to enable Skillet-Classic debugging and provide me with the output. I'll provide details on how to do that after I see the steps you provide and see if I can reproduce your error.

**Comment by matthewhively** [comment] 2021-07-23 16:14
I remember seeing this issue myself recently, but I didn't try to debug it at all.
For me I had this happen after I attempted to process a queued item while in the wrong tradeskill window (example, craft queued bandages while in cooking window). After that errored out (I forget if it was the same error), when clicking on the buttons at the top I got the same error message.

**Comment by b-morgan** [comment] 2021-07-23 19:37
I still need a step-by-step, reproducible case.

**Closed** 2021-07-23 21:44 UTC
