### ISSUE TITLE
Inscription - Unable to do Minor Inscription Research

### ISSUE THREAD

**Issue by AshenEdict** [b-morgan/Skillet-Classic#88] opened 2022-09-04 14:58 UTC
Unable to do the Minor Inscription Research within Skillet. It's greyed out and doesn't allow the craft option to go through, no errors at all. I've also noticed that the search feature seems a little wonky when it comes to trying to search up the Research. Typing in any of the full words in the name causes it to disappear from the list.

**Comment by Zereges** [comment] 2022-09-04 15:49
Somehow I assume it's because the recipe doesn't have an output (it's even missing an icon in blizz ui).

**Comment by b-morgan** [comment] 2022-09-04 16:40
The Minor Inscription Research issue is a duplicate of #84 and is fixed in [Skillet-Classic-1.48-alpha2](https://www.curseforge.com/wow/addons/skillet-classic/files/3965677). Please report back if you have problems with that release.

The search issue is a duplicate of #86 and progress will be monitored there.

**Closed** 2022-09-08 21:42 UTC
