### ISSUE TITLE
Enchanting: Skill difficulty for enchants get mixed and display incorrectly

### ISSUE THREAD

**Issue by PaCozz** [b-morgan/Skillet-Classic#16] opened 2021-06-01 00:42 UTC
Enchanting skills mix up difficulties if another profession window is opened after the enchanting window. Skills that are supposed to be yellow, show up as gray etc. UI has to be reloaded to fix this issue temporarily.

Steps to reproduce:
1.Play WoW:BCC
2. Enable Skillet-Classic
3. Log in on a character that has Enchanting profession
4. Open the enchanting profession window
5. Close enchanting profession window
6. Open First aid window
7. Close First aid window
8. Open enchanting window again
9. Observe mixed skills

Repro 5/5. Depending on which secondary profession is opened the difficulties mix up differently

Screenshot:
![WoWScrnShot_053121_192032](https://user-images.githubusercontent.com/78828265/120251818-62471380-c28b-11eb-84cd-b1f3cf0342c1.jpg)

**Comment by Dejoule** [comment] 2021-06-02 02:03
can confirm this is happening to me, it also throws LUA errors, or at least has once, but I cannot replicate that

**Comment by b-morgan** [comment] 2021-06-02 13:41
Unfortunately, I had to split my characters between Classic Era and Burning Crusade Classic and my higher level (only 71/150) Enchanter stayed on Classic Era. I have a brand new enchanter on Burning Crusade Classic but I cannot reproduce this error on either version. That means we have to cooperate in a joint troubleshooting session.

@Dejoule Please install [BugGrabber ](https://www.curseforge.com/wow/addons/bug-grabber)and [BugSack](https://www.curseforge.com/wow/addons/bugsack). If you get another Lua error, it will be captured so you can post it here and I can look at it. You may have to edit the !BugGrabber.toc file changing ##Interface: 90005 to 20501.

Skillet-Classic contains debugging statements scattered throughout the code. Normally they do nothing but can be enabled by typing in chat. The basic command is "/skillet debugshow on" which turns on output to chat and output to the per character saved variables file, Skillet-Classic.lua. "/skillet debugshow off" will turn off chat output but will leave output to the saved variables file enabled. This log is limited in size and keeps only the most recent output. It can be turned off with "/skillet debuglogging off". The performance impact of debug logging is minimal. I run with it on all the time.

In addition, there are other "levels" of debugging including "/skillet traceshow on" and "/skillet warnshow on". Status of all the debugging features is shown by "/skillet debugstatus". One more command I will probably need is "/skillet tabledump".

Normally, you do not need to capture the chat output. Its useful for me when I'm actively debugging, but in this case of remote troubleshooting, I'll only need the per character saved variables file and the global saved variables file.

Now for the actual troubleshooting steps I'd like you to perform. 

First, I see a lot of addons including a complete UI. If you have any profession / trade skill / crafting addons, please see if disabling them changes the behavior of this Skillet-Classic issue. I don't want to request only Skillet-Classic enabled unless necessary.

Second, when the Skillet-Classic frame is showing bad data, close it and reopen it to the SAME profession and let me know if that clears things up. If not, then I will need the debug log with "/skillet debuglogging on", "/skillet tracelog on", and "/skillet tabledump on".

**Comment by b-morgan** [comment] 2021-06-02 14:06
After looking at the code I think I found the problem. Please replace `...\UI\MainFrame.lua with the one from the attached 
[MainFrame.zip](https://github.com/b-morgan/Skillet-Classic/files/6585097/MainFrame.zip)
zip file.

**Comment by Dejoule** [comment] 2021-06-02 23:34
1x [ADDON_ACTION_BLOCKED] AddOn 'Skillet-Classic' tried to call the protected function 'SkilletFrameTradeButtons-Horologist:Show()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `Show'
[string "@Skillet-Classic\UI\MainFrame.lua"]:709: in function `UpdateTradeButtons'
[string "@Skillet-Classic\UI\MainFrame.lua"]:881: in function `UpdateTradeSkillWindow'
[string "@Skillet-Classic\UI\MainFrame.lua"]:2352: in function `ScrollToSkillIndex'
[string "@Skillet-Classic\Skillet-20501.nil.lua"]:1416: in function `SetSelectedSkill'
[string "@Skillet-Classic\UI\MainFrame.lua"]:2273: in function `SkillButton_OnClick'
[string "*:OnClick"]:2: in function <[string "*:OnClick"]:1

This is the code .lua I still don't know how to reliably replicate it. I don't think it's related to this issue though.

**Comment by b-morgan** [comment] 2021-06-03 01:01
@Dejoule Your assessment is correct, this has nothing to do with this issue. Please help me keep track and open a new issue.

**Comment by fireboy92k** [comment] 2021-06-03 04:54
I'm having the same issue if I can be of any help on my Enchanter.

**Comment by Dejoule** [comment] 2021-06-03 05:47
> After looking at the code I think I found the problem. Please replace `...\UI\MainFrame.lua` with the one from the attached zip file.
> 
> [MainFrame.zip](https://github.com/b-morgan/Skillet-Classic/files/6585097/MainFrame.zip)

This has since fixed my enchanting mixup issue, btw

**Comment by b-morgan** [comment] 2021-06-03 11:24
Skillet-Classic-1.26 contains the fix for this issue.

**Closed by b-morgan** 2021-06-03 11:24 UTC
