### ISSUE TITLE
Skillet - Tradewindow bug - Enchanting

### ISSUE THREAD

**Issue by Raithen88** [b-morgan/Skillet-Classic#81] opened 2022-09-01 17:31 UTC
BugReport - Enchanting

If you enchant somebody via Tradewindow, the enchant recipe ends in the shopping list

If you want to enchant again, the button wants to enchant the recipe from the enchanting list

Therefore it's necessary to delete the shopping list, if you want to do more than one enchantment via tradewindow.

**Comment by b-morgan** [comment] 2022-09-02 16:09
I have built [Skillet-Classic-1.48-alpha1](https://www.curseforge.com/wow/addons/skillet-classic/files/3963905) which doesn't yet address this issue, but it has other enchanting related fixes.

I believe if you check the option "Queue Enchant reagents", it will expose the queue contents and the buttons necessary to clear the queue (which also clears the shopping list).

**Comment by Raithen88** [comment] 2022-09-03 01:11
Yes, this works now!

**Comment by b-morgan** [comment] 2022-09-03 17:08
I believe this is a duplicate of issue #82 so I'm closing this one.

**Closed by b-morgan** 2022-09-03 17:08 UTC
