### ISSUE TITLE
Cant make minor inscription research

### ISSUE THREAD

**Issue by omgkielb** [b-morgan/Skillet-Classic#87] opened 2022-09-04 04:16 UTC
When clicking the "create" button nothing happens, cant even queue it either, doesnt show a craftable icon next to it either.
Have to disable addon to be able to craft. (ignore CD in Screenshot)

![image](https://user-images.githubusercontent.com/31836335/188297162-dab6d79d-d522-428a-99be-53096088ffe0.png)

**Comment by rfdavies** [comment] 2022-09-04 11:07
Can confirm this bug, not able to click any of the options for Minor Inscription Research.

**Comment by b-morgan** [comment] 2022-09-04 11:46
This is a duplicate of #84 and is fixed in [Skillet-Classic-1.48-alpha2](https://www.curseforge.com/wow/addons/skillet-classic/files/3965677).

**Closed** 2022-09-04 11:50 UTC
