### ISSUE TITLE
Profession windows will not open in v1.61 wrath 3.4.1

### ISSUE THREAD

**Issue by Dinoburt** [b-morgan/Skillet-Classic#136] opened 2023-01-19 20:11 UTC
Error occured in: Global
Count: 1
Message: bad argument #2 to '?' (Usage: self:SetParent([parent]))
Debug:
   [string "=[C]"]: ?
   [string "=[C]"]: SetParent()
   [string "@Interface/AddOns/Skillet-Classic/UI/MainFrame.lua"]:459: ResetTradeSkillWindow()
   [string "@Interface/AddOns/Skillet-Classic/Skillet.lua"]:1443: ShowTradeSkillWindow()
   [string "@Interface/AddOns/Skillet-Classic/Skillet.lua"]:1255: SkilletShowWindow()
   [string "@Interface/AddOns/Skillet-Classic/Skillet.lua"]:938: ?()
   [string "@Interface/AddOns/AtlasLootClassic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:109:
      ...sic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109
   [string "=[C]"]: ?
   [string "@Interface/AddOns/AtlasLootClassic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19:
      ...sic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15
   [string "@Interface/AddOns/AtlasLootClassic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: Fire()
   [string "@Interface/AddOns/Attune/Libs/AceEvent-3.0/AceEvent-3.0.lua"]:120:
      ...ace/AddOns/Attune/Libs/AceEvent-3.0/AceEvent-3.0.lua:119

Not sure if a conflict with the other addons, but clicking on professions from skill book throws the above error.

**Comment by Gunner-web** [comment] 2023-01-19 21:15
Not sure if this is related but when I open a skill I only see the Blizzard "stock" screen instead of the skillet screens.

**Comment by b-morgan** [comment] 2023-01-19 23:22
@Dinoburt, I cannot reproduce this with the information you have given me. I believe this is either an addon conflict or a corrupted install. Please manually download from [https://www.curseforge.com/wow/addons/skillet-classic/files](https://www.curseforge.com/wow/addons/skillet-classic/files) and verify the MD5, delete your current `...\Addons\Skillet-Classic` folder and reinstall. Uncheck "Load out of date AddOns" and let me know if you still have problems.

**Comment by b-morgan** [comment] 2023-01-19 23:24
@Gunner-web, How do you open your professions? Do you use an action bar button? Do you use any modifier keys like Shift, Ctrl, or Alt when you click on the button?

**Comment by Civic261** [comment] 2023-01-20 11:11
I've found from experimenting that following addons are causing this reported behaviour:
Enchantrix (part of Auctioneer Suite)
EnchantrixBarker
MobInfo2
Missing TradeSkills List (TBC)

**Comment by b-morgan** [comment] 2023-01-20 13:53
@Civic261, Thank you for that information. It will take a while for all addons to be updated and until they are, I can't resolve any conflicts with Skillet-Classic that might be caused by Skillet-Classic.

**Comment by b-morgan** [comment] 2023-01-20 17:10
This should be fixed in Skillet-Classic-1.63.

**Closed by b-morgan** 2023-01-20 17:10 UTC

**Comment by Raulfin** [comment] 2023-01-21 01:30
Had encountered this in 1.61 also, and came to report it but seems to be working after updating to 1.63.
